# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fffc999174cf2118ca4ac325c8c2492c3b4a0c8e609c9270c5d17de117a71e38a3565d1865bf1ceb4fabd84123bdaeedcc743fb2b6aea9c75ac0511d5b9a40bb

test:
  secret_key_base: 3825290aadea27bae6044ee4756c86126369041b423bd282474dc95cd0238b81aced08442f39de6013dd34e2b1e529955b10287db26944233d7916826d36322b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
